/** Indexable static marketing and docs routes for sitemap.xml */
export const STATIC_SITEMAP_ROUTES = [
  "",
  "/solutions/hvac",
  "/solutions/contractors",
  "/solutions/small-teams",
  "/hvac-time-tracking",
  "/hvac-scheduling-software",
  "/hvac-payroll-software",
  "/dispatch-software",
  "/profit-leak",
  "/hidden-profit",
  "/sample-report",
  "/about",
  "/security",
  "/support",
  "/contact",
  "/demo",
  "/book",
  "/docs",
  "/docs/owner/getting-started",
  "/docs/owner/jobs-and-projects",
  "/docs/owner/workers-and-time",
  "/docs/owner/payroll-and-export",
  "/docs/owner/reporting-and-insights",
  "/docs/owner/settings-and-security",
  "/docs/worker/first-login-and-dashboard",
  "/docs/worker/clock-and-job-workflow",
  "/docs/worker/timesheet-habits",
  "/docs/worker/common-errors-and-fixes",
  "/docs/playbooks/margin-recovery-cadence",
  "/docs/playbooks/overtime-reduction",
  "/docs/playbooks/estimate-accuracy",
  "/docs/playbooks/weekly-review-template",
  "/docs/help/troubleshooting-matrix",
  "/docs/help/faq",
  "/docs/help/glossary",
] as const;
